### ISSUE TITLE
Jobs posted are not displayed

### ISSUE THREAD

**Issue by nazimboudeffa** [nazimboudeffa/neofreelance-basic-php#5]
When positing a job, the app doesn't display them

**Comment by nazimboudeffa** [comment]
It looks like the jobs must be activated in the database

**Comment by osminosm** [comment]
I dont think its a bug, the job must be validated in admin panel normally

**Comment by nazimboudeffa** [comment]
There is the admin section where the owner of the site can activate jobs, the default credentials are admin/admin

It can be accessed from https://neofreelance.com/admin

I have sent the new pawword to you in dm from the DZDEVs Community

![dLWjFsd6gL](https://user-images.githubusercontent.com/1375686/196047793-99acddde-e7c6-4ef2-abd0-84ea2b9e21b2.png)

**Comment by osminosm** [comment]
Here is what i did : 
<img width="1174" alt="Screenshot 2022-10-16 at 18 58 25" src="https://user-images.githubusercontent.com/7093627/196048225-e7a23796-3d9a-40bd-8b89-749e93113a5f.png">

**Comment by nazimboudeffa** [comment]
On fossjobs.net it looks like they have another template or way of connecting to the admin panel

![image](https://user-images.githubusercontent.com/1375686/196048558-030a7656-77aa-4297-99b6-4e6adaa96539.png)
